# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exportdialog.ui'
#
# Created: Fri Jun 27 14:43:15 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ExportDialog(object):
    def setupUi(self, ExportDialog):
        ExportDialog.setObjectName(_fromUtf8("ExportDialog"))
        ExportDialog.resize(470, 604)
        ExportDialog.setMinimumSize(QtCore.QSize(0, 540))
        ExportDialog.setMaximumSize(QtCore.QSize(900, 967))
        self.verticalLayout_3 = QtGui.QVBoxLayout(ExportDialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.exportWidget = QtGui.QWidget(ExportDialog)
        self.exportWidget.setObjectName(_fromUtf8("exportWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.exportWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label = QtGui.QLabel(self.exportWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_15.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_13 = QtGui.QLabel(self.exportWidget)
        self.label_13.setMinimumSize(QtCore.QSize(40, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.exportSnapshotWidget = QtGui.QWidget(self.exportWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportSnapshotWidget.sizePolicy().hasHeightForWidth())
        self.exportSnapshotWidget.setSizePolicy(sizePolicy)
        self.exportSnapshotWidget.setObjectName(_fromUtf8("exportSnapshotWidget"))
        self.horizontalLayout_5.addWidget(self.exportSnapshotWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.exportWidget)
        self.label_14.setMinimumSize(QtCore.QSize(40, 0))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.layersList = QtGui.QListWidget(self.exportWidget)
        self.layersList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.layersList.setObjectName(_fromUtf8("layersList"))
        self.horizontalLayout_7.addWidget(self.layersList)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line = QtGui.QFrame(self.exportWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_19 = QtGui.QLabel(self.exportWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_32.addWidget(self.label_19)
        spacerItem2 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_32)
        self.exportTypeWidget = QtGui.QTabWidget(self.exportWidget)
        self.exportTypeWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.exportTypeWidget.setTabPosition(QtGui.QTabWidget.North)
        self.exportTypeWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.exportTypeWidget.setUsesScrollButtons(False)
        self.exportTypeWidget.setObjectName(_fromUtf8("exportTypeWidget"))
        self.shapefile_2 = QtGui.QWidget()
        self.shapefile_2.setObjectName(_fromUtf8("shapefile_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.shapefile_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.fileBrowserLabel_3 = QtGui.QLabel(self.shapefile_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileBrowserLabel_3.sizePolicy().hasHeightForWidth())
        self.fileBrowserLabel_3.setSizePolicy(sizePolicy)
        self.fileBrowserLabel_3.setMinimumSize(QtCore.QSize(0, 0))
        self.fileBrowserLabel_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fileBrowserLabel_3.setFont(font)
        self.fileBrowserLabel_3.setObjectName(_fromUtf8("fileBrowserLabel_3"))
        self.verticalLayout_2.addWidget(self.fileBrowserLabel_3)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.exportFileBox = QtGui.QLineEdit(self.shapefile_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportFileBox.sizePolicy().hasHeightForWidth())
        self.exportFileBox.setSizePolicy(sizePolicy)
        self.exportFileBox.setMinimumSize(QtCore.QSize(250, 0))
        self.exportFileBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.exportFileBox.setInputMask(_fromUtf8(""))
        self.exportFileBox.setText(_fromUtf8(""))
        self.exportFileBox.setObjectName(_fromUtf8("exportFileBox"))
        self.horizontalLayout_29.addWidget(self.exportFileBox)
        self.selectExportFileButton = QtGui.QToolButton(self.shapefile_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectExportFileButton.sizePolicy().hasHeightForWidth())
        self.selectExportFileButton.setSizePolicy(sizePolicy)
        self.selectExportFileButton.setMinimumSize(QtCore.QSize(0, 0))
        self.selectExportFileButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectExportFileButton.setObjectName(_fromUtf8("selectExportFileButton"))
        self.horizontalLayout_29.addWidget(self.selectExportFileButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.exportTypeWidget.addTab(self.shapefile_2, _fromUtf8(""))
        self.spatialite_2 = QtGui.QWidget()
        self.spatialite_2.setObjectName(_fromUtf8("spatialite_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.spatialite_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem5 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem5)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_17 = QtGui.QLabel(self.spatialite_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_36.addWidget(self.label_17)
        self.spatialiteFileBox = QtGui.QLineEdit(self.spatialite_2)
        self.spatialiteFileBox.setMinimumSize(QtCore.QSize(0, 0))
        self.spatialiteFileBox.setObjectName(_fromUtf8("spatialiteFileBox"))
        self.horizontalLayout_36.addWidget(self.spatialiteFileBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_18 = QtGui.QLabel(self.spatialite_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_37.addWidget(self.label_18)
        self.spatialiteUserBox = QtGui.QLineEdit(self.spatialite_2)
        self.spatialiteUserBox.setMinimumSize(QtCore.QSize(0, 0))
        self.spatialiteUserBox.setObjectName(_fromUtf8("spatialiteUserBox"))
        self.horizontalLayout_37.addWidget(self.spatialiteUserBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_37)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem6)
        self.exportTypeWidget.addTab(self.spatialite_2, _fromUtf8(""))
        self.postgis_2 = QtGui.QWidget()
        self.postgis_2.setObjectName(_fromUtf8("postgis_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.postgis_2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        spacerItem7 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem7)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_12 = QtGui.QLabel(self.postgis_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_40.addWidget(self.label_12)
        self.pgExportHostBox = QtGui.QLineEdit(self.postgis_2)
        self.pgExportHostBox.setText(_fromUtf8(""))
        self.pgExportHostBox.setObjectName(_fromUtf8("pgExportHostBox"))
        self.horizontalLayout_40.addWidget(self.pgExportHostBox)
        self.label_20 = QtGui.QLabel(self.postgis_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_40.addWidget(self.label_20)
        self.pgExportPortBox = QtGui.QLineEdit(self.postgis_2)
        self.pgExportPortBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pgExportPortBox.setText(_fromUtf8(""))
        self.pgExportPortBox.setObjectName(_fromUtf8("pgExportPortBox"))
        self.horizontalLayout_40.addWidget(self.pgExportPortBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_21 = QtGui.QLabel(self.postgis_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_41.addWidget(self.label_21)
        self.pgExportUserBox = QtGui.QLineEdit(self.postgis_2)
        self.pgExportUserBox.setText(_fromUtf8(""))
        self.pgExportUserBox.setObjectName(_fromUtf8("pgExportUserBox"))
        self.horizontalLayout_41.addWidget(self.pgExportUserBox)
        self.label_22 = QtGui.QLabel(self.postgis_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_41.addWidget(self.label_22)
        self.pgExportPasswordBox = QtGui.QLineEdit(self.postgis_2)
        self.pgExportPasswordBox.setText(_fromUtf8(""))
        self.pgExportPasswordBox.setObjectName(_fromUtf8("pgExportPasswordBox"))
        self.horizontalLayout_41.addWidget(self.pgExportPasswordBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_23 = QtGui.QLabel(self.postgis_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_42.addWidget(self.label_23)
        self.pgExportDatabaseBox = QtGui.QLineEdit(self.postgis_2)
        self.pgExportDatabaseBox.setText(_fromUtf8(""))
        self.pgExportDatabaseBox.setObjectName(_fromUtf8("pgExportDatabaseBox"))
        self.horizontalLayout_42.addWidget(self.pgExportDatabaseBox)
        self.label_24 = QtGui.QLabel(self.postgis_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_42.addWidget(self.label_24)
        self.pgExportSchemaBox = QtGui.QLineEdit(self.postgis_2)
        self.pgExportSchemaBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pgExportSchemaBox.setText(_fromUtf8(""))
        self.pgExportSchemaBox.setObjectName(_fromUtf8("pgExportSchemaBox"))
        self.horizontalLayout_42.addWidget(self.pgExportSchemaBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_25 = QtGui.QLabel(self.postgis_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_43.addWidget(self.label_25)
        self.pgExportTableBox = QtGui.QLineEdit(self.postgis_2)
        self.pgExportTableBox.setText(_fromUtf8(""))
        self.pgExportTableBox.setPlaceholderText(_fromUtf8(""))
        self.pgExportTableBox.setObjectName(_fromUtf8("pgExportTableBox"))
        self.horizontalLayout_43.addWidget(self.pgExportTableBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_43)
        self.exportTypeWidget.addTab(self.postgis_2, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.exportTypeWidget)
        spacerItem8 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem8)
        self.openLayerCheckbox = QtGui.QCheckBox(self.exportWidget)
        self.openLayerCheckbox.setObjectName(_fromUtf8("openLayerCheckbox"))
        self.verticalLayout_4.addWidget(self.openLayerCheckbox)
        self.line_4 = QtGui.QFrame(self.exportWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_4.addWidget(self.line_4)
        self.progressBarExport = QtGui.QProgressBar(self.exportWidget)
        self.progressBarExport.setProperty("value", 0)
        self.progressBarExport.setObjectName(_fromUtf8("progressBarExport"))
        self.verticalLayout_4.addWidget(self.progressBarExport)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.exportButtonBox = QtGui.QDialogButtonBox(self.exportWidget)
        self.exportButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.exportButtonBox.setObjectName(_fromUtf8("exportButtonBox"))
        self.horizontalLayout_6.addWidget(self.exportButtonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.exportWidget)

        self.retranslateUi(ExportDialog)
        self.exportTypeWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ExportDialog)

    def retranslateUi(self, ExportDialog):
        ExportDialog.setWindowTitle(_translate("ExportDialog", "Export", None))
        self.exportWidget.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label.setText(_translate("ExportDialog", "Export from:", None))
        self.label_13.setText(_translate("ExportDialog", "Version", None))
        self.label_14.setText(_translate("ExportDialog", "Layer", None))
        self.label_19.setText(_translate("ExportDialog", "Export to:", None))
        self.fileBrowserLabel_3.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.fileBrowserLabel_3.setText(_translate("ExportDialog", "Filename:", None))
        self.exportFileBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.exportFileBox.setPlaceholderText(_translate("ExportDialog", "Enter a file location", None))
        self.selectExportFileButton.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.selectExportFileButton.setText(_translate("ExportDialog", "...", None))
        self.exportTypeWidget.setTabText(self.exportTypeWidget.indexOf(self.shapefile_2), _translate("ExportDialog", "Shapefile", None))
        self.label_17.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_17.setText(_translate("ExportDialog", "database:", None))
        self.spatialiteFileBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.spatialiteFileBox.setPlaceholderText(_translate("ExportDialog", "database.sqlite", None))
        self.label_18.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_18.setText(_translate("ExportDialog", "user:", None))
        self.spatialiteUserBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.spatialiteUserBox.setPlaceholderText(_translate("ExportDialog", "user", None))
        self.exportTypeWidget.setTabText(self.exportTypeWidget.indexOf(self.spatialite_2), _translate("ExportDialog", "SpatiaLite", None))
        self.label_12.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_12.setText(_translate("ExportDialog", "host:", None))
        self.pgExportHostBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.pgExportHostBox.setPlaceholderText(_translate("ExportDialog", "localhost", None))
        self.label_20.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_20.setText(_translate("ExportDialog", "port:", None))
        self.pgExportPortBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.pgExportPortBox.setPlaceholderText(_translate("ExportDialog", "5432", None))
        self.label_21.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_21.setText(_translate("ExportDialog", "user:", None))
        self.pgExportUserBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.pgExportUserBox.setPlaceholderText(_translate("ExportDialog", "postgres", None))
        self.label_22.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_22.setText(_translate("ExportDialog", "password:", None))
        self.pgExportPasswordBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.pgExportPasswordBox.setPlaceholderText(_translate("ExportDialog", "postgres", None))
        self.label_23.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_23.setText(_translate("ExportDialog", "database:", None))
        self.pgExportDatabaseBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.pgExportDatabaseBox.setPlaceholderText(_translate("ExportDialog", "database", None))
        self.label_24.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_24.setText(_translate("ExportDialog", "schema:", None))
        self.pgExportSchemaBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.pgExportSchemaBox.setPlaceholderText(_translate("ExportDialog", "public", None))
        self.label_25.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.label_25.setText(_translate("ExportDialog", "table:", None))
        self.pgExportTableBox.setStyleSheet(_translate("ExportDialog", "#fileImportHelp {\n"
"   color: blue;\n"
"}", None))
        self.exportTypeWidget.setTabText(self.exportTypeWidget.indexOf(self.postgis_2), _translate("ExportDialog", "PostGIS", None))
        self.openLayerCheckbox.setText(_translate("ExportDialog", "Open in QGIS after exporting", None))

